# Site settings
title: REDLINE | Raleigh's Premier Party Rock Band
email: redlinebandnc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Raleigh’s Premier Party Rock Band
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://redlinenc.com" # the base hostname & protocol for your site
twitter_username: redlinenc



# Build settings
markdown: kramdown
exclude: 
    - s3_website.yml
